services:
  doctrine.settings.odm:
    class: Vainyl\Doctrine\ODM\DoctrineDocumentSettings
    arguments: ['@doctrine.settings', 'admin', 'entitymap', 'odm.yml', '/tmp', 'Proxy', 'Hydrator']
  doctrine.mapping.driver.document.factory:
    class: Vainyl\Doctrine\ODM\Factory\DoctrineDocumentMappingDriverFactory
    arguments: ['@doctrine.mapping.path.provider']
  doctrine.mapping.driver.document:
    class: Doctrine\Common\Persistence\Mapping\Driver\MappingDriver
    factory: ['@doctrine.mapping.driver.entity.factory', 'create']
    arguments:
      - '@doctrine.settings.entity'
  doctrine.configuration.odm:
    class: Doctrine\ODM\MongoDB\Configuration
    factory: ['@doctrine.configuration.factory.odm', 'getConfiguration']
    arguments:
      - '@app.environment'
      - '@doctrine.settings.odm'
      - '@doctrine.mapping.driver.document'
  doctrine.configuration.factory.odm:
    class: Vainyl\Doctrine\ODM\Factory\DoctrineODMConfigurationFactory
  doctrine.document.manager:
    class: Vainyl\Doctrine\ODM\DoctrineDocumentManager
    factory: ['@doctrine.document.manager.factory', 'create']
    arguments:
      - '@database.doctrine.odm'
      - '@doctrine.configuration.odm'
      - '@doctrine.event.manager'
      - '@time.factory'
    tags:
      - {name: doctrine.manager, alias: odm}
      - {name: domain.storage, alias: doctrine.odm}
  doctrine.document.manager.factory:
    class: Vainyl\Doctrine\ODM\Factory\DoctrineDocumentManagerFactory
  doctrine.document.metadata.factory:
    class: Doctrine\ODM\MongoDB\Mapping\ClassMetadataFactory
    factory: ['@doctrine.document.manager', 'getMetadataFactory']
  collection.factory.sequence.document:
    decorates: collection.factory.sequence
    decoration_priority: 500
    class: Vainyl\Doctrine\ODM\Operation\Decorator\DoctrineCollectionFactoryDecorator
    arguments: ['@collection.factory.sequence.document.inner', '@doctrine.document.manager']
  collection.factory.set.document:
    decorates: collection.factory.set
    decoration_priority: 500
    class: Vainyl\Doctrine\ODM\Operation\Decorator\DoctrineCollectionFactoryDecorator
    arguments: ['@collection.factory.set.document.inner', '@doctrine.document.manager']
  document.operation.factory.doctrine:
    class: Vainyl\Doctrine\ODM\Operation\Factory\DoctrineDocumentOperationFactory
    arguments: ['@collection.factory.sequence', '@doctrine.document.manager']
    tags:
      - {name: document.operation.factory, alias: doctrine}
  app.bootstrapper.doctrine.odm.annotation:
    class: Vainyl\Doctrine\ODM\Bootstrapper\DoctrineAnnotationBootstrapper
    tags:
      - {name: bootstrapper}
  app.bootstrapper.doctrine.odm.type:
    class: Vainyl\Doctrine\ODM\Bootstrapper\DoctrineTypeBootstrapper
    arguments: ['@time.factory']
    tags:
      - {name: bootstrapper}
  database.factory.doctrine.odm:
    class: Vainyl\Doctrine\ODM\Factory\DoctrineODMDatabaseFactory
    arguments: ['@connection.storage', '@doctrine.event.manager']
  document.hydrator.doctrine:
    class: Vainyl\Doctrine\ODM\DoctrineDocumentHydrator
    arguments:
      - '@hydrator.registry'
      - '@domain.storage'
      - '@doctrine.document.metadata.factory'
    tags:
      - {name: document.hydrator, alias: doctrine}
